name: Hello World Container

on:
  workflow_dispatch:
  push:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  hello:
    runs-on: self-hosted
    container:
      image: node:24
    steps:
      - run: | 
          echo starting sleep
          sleep 60
          echo "never see me!"
          exit 1
      - run: echo "this step should never run!"
  # fail:
  #   runs-on: self-hosted
  #   container:
  #     image: node:24
  #   steps:
  #     - run: exit 1
      
